### ISSUE TITLE
Improve scroll behavior by studying Surfingkeys

### ISSUE THREAD

**Issue by AdamWagner** [alexherbo2/scroll.js#1]
Hi Alex. I'm really impressed by Krabby – amazing work!
Of all the navigate-by-keyboard extensions, the Krabby codebase is the easiest to understand (even easier than Saka Key, IMO).

IMO, Krabby's weakest functionality is scrolling behavior: it's laggy and twitchy compared to Surfingkeys (I can provide a proper report if you can't reproduce, but I think it will be easy to see the shortcomings)

The Surfingkeys codebase may be convoluted, but the scrolling behavior is the smoothest of all the options (Vimium, C-vim, Triadactyl, Saka Key, etc). Porting the smoothness of Surfingkeys' smooth scrolling to Krabby would make Krabby my preferred extension for keyboard navigation.

The scrolling functionality in Surfingkeys resides here:
https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/normal.js#L513

**Comment by alexherbo2** [comment]
[Saka Key] is god-like to me, in terms of architecture.  It misses so much features, but its codebase is the cleanest I have seen.

I’ll take a look.

[Saka Key]: https://key.saka.io

**Comment by alexherbo2** [comment]
@AdamWagner I do it, or do you want to make a PR?

**Comment by AdamWagner** [comment]
@alexherbo2 Thanks for the offer – I will try to untangle Surfingkeys scroll functionality and make a PR.  🤞

**Comment by alexherbo2** [comment]
@AdamWagner I’m really happy with that change, thanks for the report. 🦀

**Comment by AdamWagner** [comment]
@alexherbo2 I re-installed Krabby on a fresh Chrome profile and started to dig into the scrolling behavior.

Your last two commits dramatically improved scrolling via `j` and `k`, with a couple of very minor changes! Really nicely done. 

Big-step scrolling with `J` and `K` is still sticky during key repeat, so I'll try to smooth that out.

**Comment by alexherbo2** [comment]
<kbd>J</kbd> and <kbd>K</kbd>, for `pageDown` and `pageUp`, use the built-in [`scrollBy()`] function with `behavior` option being set to `smooth`.

It’s just a matter of making them using `animate()`.

[`scrollBy()`]: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollBy

**Comment by AdamWagner** [comment]
@alexherbo2 Thanks. As I played with it, I realized `pageDown` and `pageUp` weren't intended to be repeated.

I (mis)use `pageDown` and `pageUp` as "scroll faster". For my use, I'm pretty happy with these tweaks: https://github.com/AdamWagner/scroll.js/commit/2959b420520c8b6e11cb04e00b93c302e45c7160

If you have a chance, let me know what you think.

**Comment by alexherbo2** [comment]
It looks awesome, really, and the implementation looks clean.

- I noticed a regression of the small scroll down and up functionalities: there is a tiny pause after the first scroll, before the smooth scrolling continues.

- Is there a way to preserve `pageDown` and `pageUp` methods when a single key is released?

- `fastFactor` could be removed if we can preserve the functionality.

> _[The user interface]_ Customizability should be achieved via programmability, not an enormous inventory of options that interact with each other in obscure ways.

- I find the idea of `friction` and `longThrow` really awesome.

- Can you detail a bit how they work (by documenting the code)?

- What does `step` → `amt` name change is for?

- I prefer real world variable names when possible, instead of abbreviations.

- I prefer to not change style (as for `_event` and `once`), at least not in the same commit and / or PR.

- For coding style, I prefer to not add `;` at the end of statements and `,` after the last field element (as in `directions`).

- [Public static fields] are not supported in Firefox (`static directions`), you will have to use a similar approach than in [Modal]:

``` javascript
class Modal {
  // To do: Use public static fields when supported by Firefox
  // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields#Public_static_fields
  static MODIFIER_KEYS() {
    return ['Shift', 'Control', 'Alt', 'Meta']
  }
}
```

- I’m not sure if `directions` should be capitalized or kept lowercase, as it’s static. 🤔

- Finally, I’m all in to embrace \o/ smooth scrolling only.

> _[Configurability is the root of all evil]_ Every configuration option in a program is a place where the program is too stupid to figure out for itself what the user really wants, and should be considered a failure of both the program and the programmer who implemented it.

[Modal]: https://github.com/alexherbo2/modal.js
[Public static fields]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields#Public_static_fields
[Configurability is the root of all evil]: https://fishshell.com/docs/current/design.html#design-configurability
[The user interface]: https://elv.sh/ref/philosophy.html#the-user-interface

**Comment by alexherbo2** [comment]
(While experimenting with the new changes, have you updated [`krabby.js`] to pass the [`repeat`] argument to <kbd>J</kbd> and <kbd>K</kbd>?)

[`krabby.js`]: https://github.com/alexherbo2/krabby/blob/master/src/krabby.js
[`repeat`]: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat

**Comment by alexherbo2** [comment]
@AdamWagner I added your work and gave you credit in the [README][Credits] page.  I hope that is ok.

[Credits]: https://github.com/alexherbo2/scroll.js#credits
